### ISSUE TITLE
wf9a5m75 I need your help please

### ISSUE THREAD

**Issue by JamesSlater** [wf9a5m75/ionic-googlemaps-demo#10]
I am new to this and cannot find how to report an issue for 'https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4' which I am referring to.

I am receiving a blank white area where the maps should be displayed. I can still see the red border around where the map should be. I have been trying for hours and now have completely copy and pasted your code for the demo and it still does not work.

Here is a link to my repo: http://github.com/JamesSlater/app

The maps page is displayed on a modal from tapping the pin icon on the Contact page, to give you a bit of background.

I hope you have time to get back to me. Thanks in advance.

**Comment by wf9a5m75** [comment]
> The maps page is displayed on a modal 

This plugin can not display a map in a modal.
https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

**Comment by JamesSlater** [comment]
> > The maps page is displayed on a modal
> 
> This plugin can not display a map in a modal.
> https://github.com/mapsplugin/cordova-plugin-googlemaps#how-does-this-plugin-work-android-ios

Oh I see. I'll change that now and let you know if I have any further questions.
Thanks for the quick response!
