### ISSUE TITLE
BaseArrayClass

### ISSUE THREAD

**Issue by ThorvaldAagaard** [wf9a5m75/ionic-googlemaps-demo#2]
In the documentation there are 3 events

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/README.md

In the Ionic Wrapper, there are 4 events:

    on(event: 'insert_at' | 'remove_at' | 'set_at' | 'finish'): Observable<any>;

In the demo-code for native js, an event called 'error' is used

      mvcArray.on('error', function(error) {
        console.log(error);
      });
      mvcArray.on('insert_at', function(index) {

        // Get a result
        var geocodeResult = mvcArray.getAt(index);
        if (geocodeResult.length > 0) {

          latLngBounds.extend(geocodeResult[0].position);

          map.addMarker({
            'position': geocodeResult[0].position,
            'title':  JSON.stringify(geocodeResult)
          }, function(marker) {
            markers.push(marker);
          });
        } else {
          markers.push(null);
        }
      });

      mvcArray.on('finish', function() {
        isRunning = false;
      });

**Comment by wf9a5m75** [comment]
BaseArrayClass fires only `insert_at`, `set_at`, and `remove_at`.

However, Geocoder fires `finish` when all results are received.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/Geocoder.js#L34

**Comment by ThorvaldAagaard** [comment]
Ok. I will just remove listening on the error-event from the demo-app

**Comment by ThorvaldAagaard** [comment]
Looking at Geocode.js I can see that the `error` is from there, so it should be added to the Ionic Wrapper

**Comment by wf9a5m75** [comment]
Yes, you are right. Should be listed.

Please add the `error` event in the list, then please commit to https://github.com/wf9a5m75/ionic-native (master branch)

**Comment by wf9a5m75** [comment]
I fixed the Geocoder.geocode (as you may know). So there is no need to listed up the event names.

Actually, because the BaseArrayClass extends BaseClass, so all event names have to acceptable.
(I mean any event names have to work with `on()`, `one` and `off`)
