### ISSUE TITLE
BaseClass question

### ISSUE THREAD

**Issue by ThorvaldAagaard** [wf9a5m75/ionic-googlemaps-demo#3]
The result returned from geocode with an array as input is of type   

    mvcArray: BaseArrayClass<GeocoderResult>

When calling
    
    mvcArray.on('insert_at') 

the ionicWrapper has this signature

        on(event: 'insert_at' | 'remove_at' | 'set_at' | 'finish'): Observable<any>;

so expecting an observable I subscribe, but that results in 

    Cannot read property 'subscribe' of undefined

Looking in BaseClass.js it looks like another signature is expected as the code is:

    self.on = function(eventName, callback) {
      if (!eventName || !callback || typeof callback !== "function") {
        return;
      }

So it expects a callback function

**Comment by wf9a5m75** [comment]
How about `.then()` instead of `.subscribe()`?

**Comment by ThorvaldAagaard** [comment]
Not allowed for Observable. But changing the type to Promise will allow that function and is probably the fix

**Comment by wf9a5m75** [comment]
Morning

**Comment by wf9a5m75** [comment]
I finally came back to this project. I'm trying to catch up this issue, just a moment please.

**Comment by wf9a5m75** [comment]
I checked the @ionic-native/src/plugins/google-maps/index.ts

- `then` is for one time event.
  ```TypeScript
     map.addMarker({...}).then(() => {});
  ```

- `subscribe` is for the event more than one time (it means `addEventListener`)
    ```TypeScript
       map.on(GoogleMapsEvent.CAMERA_CHANGE).subscribe(()=>{});
    ```

BaseArrayClass fires `insert_at`, `set_at` and `remove_at` events more than one time,
the code should use `subscribe`.

```TypeScript
let baseArrayClass = new BaseArrayClass();
baseArrayClass.on('insert_at').subscribe(() => {

});
```

**Comment by ThorvaldAagaard** [comment]
Marker is working fine and as expected

```TypeScript
      var markers = new BaseArrayClass([]);
      markers.on('insert_at').subscribe(() => {
      });
```
note that BaseArrayClass does not have a default constructor in the Ionic wrapper

The problem is this one

```TypeScript

    self.geocoder.geocode({
      // US Capital cities
      "address": [
        "Montgomery, AL, USA", "Juneau, AK, USA", "Phoenix, AZ, USA",
....
        "Providence, RI, USA", "Columbia, SC, USA", "Pierre, SD, USA",
        "Nashville, TN, USA", "Austin, TX, USA", "Salt Lake City, UT, USA",
        "Montpelier, VT, USA", "Richmond, VA, USA", "Olympia, WA, USA",
        "Charleston, WV, USA", "Madison, WI, USA", "Cheyenne, Wyoming, USA"
      ]
    }).then((mvcArray: BaseArrayClass<GeocoderResult>) => {
     // Init some other stuff
      mvcArray.on('insert_at').subscribe((index) => {

      });
```

When the statement is executed I get the error 

    Cannot read property 'subscribe' of undefined

I added a breakpoint in BaseClass.js 

```TypeScript
    self.on = function(eventName, callback) {
      if (!eventName || !callback || typeof callback !== "function") {
        return;
      }
 ```
and on this call callback is undefined

Looking at javascript console it looks like this
![image](https://user-images.githubusercontent.com/10560652/28936627-90998e62-7888-11e7-8c0f-55648b45a8a4.png)

Pressing F11 (single step) results in this:

![image](https://user-images.githubusercontent.com/10560652/28936665-b43e5118-7888-11e7-9553-e436b90385ce.png)

**Comment by wf9a5m75** [comment]
>note that BaseArrayClass does not have a default constructor in the Ionic wrapper

It seems BaseArrayClass of the ionic wrapper has default constructor.
https://github.com/wf9a5m75/ionic-native/blob/57179a125b66afbcb5ea0c5f6aa27be6d1423a6c/src/%40ionic-native/plugins/google-maps/index.ts#L557-L565

**Comment by wf9a5m75** [comment]
I found the reason.

The BaseArrayClass of ionic wrapper extends `IonicNativePlugin`

```TypeScript
export class BaseArrayClass<T> extends IonicNativePlugin {
```

But the original BaseArrayClass extends `BaseClass`

```js
utils.extend(BaseArrayClass, BaseClass);
```

That's the reason.

**Comment by wf9a5m75** [comment]
Hence, the BaseArrayClass should be like this:

```TypeScript
export class BaseArrayClass<T> extends BaseClass {
```

**Comment by ThorvaldAagaard** [comment]
Ok, I will update that

**Comment by wf9a5m75** [comment]
Thank you :)

**Comment by ThorvaldAagaard** [comment]
I have changed that but still have the same problem with the subscribe.

But I did look in Geocode.js where the mvcArray is created

```TypeScript
    if (geocoderRequest[requestProperty] instanceof Array || 
    Array.isArray(geocoderRequest[requestProperty])) {
        //-------------------------
        // Geocoder.geocode({
        //   address: [
        //    "Kyoto, Japan",
        //    "Tokyo, Japan"
        //   ]
        // })
        //-------------------------
        requestCnt = geocoderRequest[requestProperty].length;
        mvcResults = common.createMvcArray();
        for (i = 0; i < requestCnt; i++) {
          mvcResults.push(-1, true);
        }
```
the createMvcArray() looks like this

```TypeScript
function createMvcArray(array) {
    var mvcArray;
    if (array && typeof array.getArray === "function") {
        mvcArray = new BaseArrayClass(array.getArray());
        array.on('set_at', function(index) {
            var value = array.getAt(index);
            value = "position" in value ? value.getPosition() : value;
            mvcArray.setAt(index, value);
        });
        array.on('insert_at', function(index) {
            var value = array.getAt(index);
            value = "position" in value ? value.getPosition() : value;
            mvcArray.insertAt(index, value);
        });
        array.on('remove_at', function(index) {
            mvcArray.removeAt(index);
        });

    } else {
        mvcArray = new BaseArrayClass(!!array ? array.slice(0) : undefined);
    }
    return mvcArray;
```
So the BaseArrayClass is instantiated with an undefined type, could that be the issue - And I am just guessing, haven't still figured all the aspects of the mapping out :-)

**Comment by wf9a5m75** [comment]
Um, I will catch up you. Just a moment please.

**Comment by wf9a5m75** [comment]
@ThorvaldAagaard I fixed the BaseArrayClass definition. Please `git pull`, `npm run build google-maps`, then reinstall `npm uninstall @ionic-native/google-maps; npm install (path to)/ionic-native/dist/\@ionic-native/google-maps`

https://github.com/wf9a5m75/ionic-native/commit/2c7e686d121f5b6054ed597051c2aba86aaf3ab4

**Comment by ThorvaldAagaard** [comment]
Great, I will test the change, it almost the same as the one I made, but I can see you are instantiating the property a different way then I did

    this._objectInstance = GoogleMaps.getPlugin().BaseArrayClass(initialData); 

I will get back with the result in a moment

**Comment by ThorvaldAagaard** [comment]
Hmm, 

    mvcArray.on('insert_at').subscribe((index) => {
    });

still executes the on() method on BaseClass directly with an undefined callback

![image](https://user-images.githubusercontent.com/10560652/28943978-132c2dd6-78a1-11e7-85b9-6b817544af21.png)

but 

      var markers = new BaseArrayClass([]);
      markers.on('insert_at').subscribe(() => {
      });

executes this method

![image](https://user-images.githubusercontent.com/10560652/28944077-740ddc12-78a1-11e7-8669-d09f09525438.png)

Both are of type BaseArrayClass
![image](https://user-images.githubusercontent.com/10560652/28944163-d77f0bae-78a1-11e7-980e-3e1bac5ee560.png)

but it is like the working one has an outer level 
![image](https://user-images.githubusercontent.com/10560652/28944232-15e0a40c-78a2-11e7-83c2-26244ca3d81d.png)

_objectInstance

![image](https://user-images.githubusercontent.com/10560652/28944718-d962a410-78a3-11e7-9fcc-07e598c88810.png)

This is only executed for the working one

    function BaseArrayClass(initialData) {
        var _this = _super.call(this) || this;
        _this._objectInstance = GoogleMaps.getPlugin().BaseArrayClass(initialData);
        return _this;
    }

whereas the mvcArray is instantiated directly. 

I can see in Common.js the reference to BaseArrayClass is the one in BaseArrayClass.js and not the definition in the Ionic-wrapper.

But I have no idea about how to fix that

**Comment by wf9a5m75** [comment]
Sorry, I finally came back. I will check this deeply from now.

**Comment by ThorvaldAagaard** [comment]
No problem. I am learning, but its bedtime here now

**Comment by wf9a5m75** [comment]
Yap. Please have a good sleep. I'm also still learning. I will update.

**Comment by wf9a5m75** [comment]
@ThorvaldAagaard I fixed the bug of BaseArrayClass and Geocoder.geocode.
And I also created the page of Geocoder/geocoding.

Please `git pull` both @ionic-native repository and this repository.

**Comment by ThorvaldAagaard** [comment]
Working fine, thus there seems to be a minor error but I will close this and create a new issue
