### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by ThorvaldAagaard** [wf9a5m75/ionic-googlemaps-demo#4]
The code for 
```TypeScript
/*****************************************************************************
 * LatLngBounds Class
 *****************************************************************************/
var LatLngBounds = function() {
    Object.defineProperty(this, "type", {
        value: "LatLngBounds",
        writable: false
    });

    var args = [];
    if (arguments.length === 1 &&
        typeof arguments[0] === "object" &&
        "push" in arguments[0]) {
        args = arguments[0];
    } else {
        args = Array.prototype.slice.call(arguments, 0);
    }
    for (var i = 0; i < args.length; i++) {
        if ("lat" in args[i] && "lng" in args[i]) {
            this.extend(args[i]);
        }
    }
};
```
fails if called like this
```TypeScript
let latLngBounds = new LatLngBounds();
```
but works ok if called this way
```TypeScript
let latLngBounds = new LatLngBounds([]);
```
The error:
vendor.js:1443 ERROR Error: Uncaught (in promise): TypeError: Cannot use 'in' operator to search for 'lat' in undefined
TypeError: Cannot use 'in' operator to search for 'lat' in undefined

**Comment by wf9a5m75** [comment]
Did you `git pull` of `https://github.com/wf9a5m75/ionic-native/`, `npm run build google-maps` and `npm install (path to)/dist/@ionic-native/google-maps`?

Because I fixed this yesterday.
The constructor of `LatLngBounds` is now:

```TypeScript
  constructor(southwestOrArrayOfLatLng?: LatLng | LatLng[], northeast?: LatLng) {
    let args = !!northeast ? [southwestOrArrayOfLatLng, northeast] : southwestOrArrayOfLatLng;
    this._objectInstance = new (GoogleMaps.getPlugin()).LatLngBounds(args);
  }
```

https://github.com/wf9a5m75/ionic-native/blob/master/src/%40ionic-native/plugins/google-maps/index.ts#L1707

**Comment by ThorvaldAagaard** [comment]
Yes I'm on latest. The fix is fine and allowing an empty signature as constructor. Problem occurs when constructor is called with no parameters

**Comment by wf9a5m75** [comment]
I work this line without no problem.
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/geocoder/geocoding/geocoding.ts#L130

**Comment by ThorvaldAagaard** [comment]
Version af Android? I know it works for you. Just verify if the failing statement is executed in your case

**Comment by wf9a5m75** [comment]
I tested on Android 6.0.1.
But this is JS problem, all code should work as same on any OS.

**Comment by ThorvaldAagaard** [comment]
I'm not sure the JS-version is the same on all platforms. I am running on 7.something.

But it fails here, so I can show you the call stack later. 

Is it possible for you to inspect args[i] prior to the search?

**Comment by ThorvaldAagaard** [comment]
When calling like this
```Typescript
    }).then((mvcArray: BaseArrayClass<GeocoderResult>) => {

        let latLngBounds = new LatLngBounds();
        let markers = new BaseArrayClass();

        mvcArray.on('error').subscribe((error) => {
          console.log(error);
        });
```
and setting a breakpoint here
![image](https://user-images.githubusercontent.com/10560652/28988548-98c5d3aa-7970-11e7-9163-3802a35f0dd8.png)

you can see that the array arg contains one element "undefined"

If I on the other hand uses this to make the call (Define LatLngBounds with an empty array)
```Typescript
    }).then((mvcArray: BaseArrayClass<GeocoderResult>) => {

        let latLngBounds = new LatLngBounds([]);
        let markers = new BaseArrayClass();

        mvcArray.on('error').subscribe((error) => {
          console.log(error);
        });
```
the result is
![image](https://user-images.githubusercontent.com/10560652/28988798-f4bd5150-7971-11e7-85e6-15b14023b4d2.png)
where arg now is an empty array, and the code works fine.

I think that
```Typescript
constructor(southwestOrArrayOfLatLng?: LatLng | LatLng[], northeast?: LatLng);
```
that allows 0, or 1 of 2 parameters, but the code checks to see if the first element is an array, and if not then assumes its LatLng that has been passed, so it should check for no parameters like
```Typescript
    var args = [];
    if (arguments.length === 1 &&
        typeof arguments[0] === "object" &&
        "push" in arguments[0]) {
        args = arguments[0];
    } else {
        if (arguments[0] != undefined) {
            args = Array.prototype.slice.call(arguments, 0);
        }
    }
    for (var i = 0; i < args.length; i++) {
        if ("lat" in args[i] && "lng" in args[i]) {
            this.extend(args[i]);
        }
    }
```
Then it works fine for me in both situations

**Comment by wf9a5m75** [comment]
Oh, sorry, I haven't caught you up yet..
But thank you for inspecting.

**Comment by ThorvaldAagaard** [comment]
No need to excuse, I haven't been waiting :-)

 It could probably also be fixed here
![image](https://user-images.githubusercontent.com/10560652/28989581-813955b2-7976-11e7-989a-f95a64dd6795.png)

**Comment by wf9a5m75** [comment]
@ThorvaldAagaard 

Actually, I fixed this issue long time ago (especially on the marker cluster development).
And I merged the most of all code to the current multiple_maps branch.
I guess I merged after you tested.
Then the code becomes like this:

```js
    for (var i = 0; i < args.length; i++) {
        if (args[i] && args[i] && "lat" in args[i] && "lng" in args[i]) {
            this.extend(args[i]);
        }
    }
```

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/93e138a8cefcc7efbb3fea63e67c2f2365453edf/www/LatLngBounds.js#L22

Since the code `if (args[i]` blocks `null` and `undefined`, currently work fine if you execute `new  LatLng(undefined)`.

Please reinstall the plugin

**Comment by ThorvaldAagaard** [comment]
Hmm, interesting my version is still the code without the test.

I can see you committed the change 7th of July, and I can see I installed the plugin at the 28th of July, and in the demo project at 3rd of August

Anyway doing a clean install gave me the fixed version

By the way you might have merged it in twice as it now reads:

```typescript
args[i] && args[i] &&
```

**Comment by wf9a5m75** [comment]
Opps!

**Comment by wf9a5m75** [comment]
Fixed it!
