### ISSUE TITLE
Custom Controls

### ISSUE THREAD

**Issue by ThorvaldAagaard** [wf9a5m75/ionic-googlemaps-demo#6]
Is it possible using this plugin to add a custom control, like described in https://developers.google.com/maps/documentation/javascript/examples/control-custom

**Comment by wf9a5m75** [comment]
Yes, possible. That's why JS developers use this plugin.
Just put any HTML elements on the map.

**Comment by wf9a5m75** [comment]
For example,

```html
<div class="map" id="map_canvas1">
  <button ion-button (click)="onButton1_click($event)" >Click here</button></span>
</div>
```

**Comment by wf9a5m75** [comment]
But you don't need to put the element inside the map div tag.
This plugin recognizes z-index also.
If you set higher z-index than the map div, it is clickable.

**Comment by ThorvaldAagaard** [comment]
So instead of 
```Typescript
        // Create the DIV to hold the control and call the CenterControl()
        // constructor passing in this DIV.
        var centerControlDiv = document.createElement('div');
        var centerControl = new CenterControl(centerControlDiv, map);

        centerControlDiv.index = 1;
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(centerControlDiv);
```
I just add a div and reference that div in the code like this
```Typescript
        var centerControlDiv = document.getElementById('mapcustomdiv');
        var centerControl = new CenterControl(centerControlDiv, map);
        centerControlDiv.index = 1;
```
I know this could be done with styling, but just as an example of overlaying the map with custom html

**Comment by wf9a5m75** [comment]
https://github.com/wf9a5m75/ionic-googlemaps-demo/blob/master/src/pages/map/get-map/get-map.html#L121-L124
