### ISSUE TITLE
about the decoder did it changed? because it doesn't return an ILatLng[] but a LatLng instead.

### ISSUE THREAD

**Issue by Cariaga** [wf9a5m75/ionic-googlemaps-demo#9]
```TypeScript
 let encodedPath: string = 'c{|xHbo|OSnFrSjW~M{EnFwVz@wy@vQsq@cBoUzJ{EzObBrIcLfE~C~H{Y~C~CfOgY{EjM{EgTcLzTsSwQcGf@IoKgJSkMsb@RkR' +
    'vVkRDon@SooBvBsXbGgE{@{EfE{EwLsXgEo{AcVgw@kRc|A_q@seAcLg@bBvQkCnKcGjCwQsSkM?cL{YjHrS{J~HgOwBgOjf@{Jj' +
    'u@cLjRcGz^oUjW{Tni@f@jRsIj\wBjf@sNbo@wG~iArDnlArIj\bGfr@bQf^~WrSnPvVfOjHnURzc@cQbQzc@nUrtAbBfYkC~M~H' +
    'nZ~Mz^f^_N~MrDbBwQkWsXR{E';

    let points: ILatLng[] = Encoding.decodePath(encodedPath);
```

**Comment by wf9a5m75** [comment]
This will be fixed in the next release.
https://github.com/ionic-team/ionic-native/commit/f11be24f7463e342d314cd7218519bae101ed07a

**Comment by Cariaga** [comment]
thanks for the heads up i hope this gets fixed soon.

**Comment by wf9a5m75** [comment]
We are waiting the next release of `ionic-native` plugins.

**Comment by wf9a5m75** [comment]
Oh, sorry for update.
The `@ionic-native/google-maps@4.6.1` is now available on npm.
https://www.npmjs.com/package/@ionic-native/google-maps

Please reinstall with `npm install @ionic-native/google-maps@4.6.1`.
